language: node_js

node_js:
    - "node"
    - "11"
    - "10"
    - "8"
    - "6"

sudo: false

git:
    submodules: false

matrix:
    allow_failures:
        - node_js: "6"
        - node_js: "8"

before_script:
    - npm install

script:
    - npm test

after_success:
    - npm run report-coveralls
    - npm run report-codecov
